---
# PLAY 1 — Deploy Apache Web Server on Ubuntu Clients
- name: Deploy Apache Webserver
  hosts: ubuntu_clients
  become: yes
  vars:
    my_name: "Ebsiy Anslem"
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Start and enable Apache
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Create custom index.html
      copy:
        dest: /var/www/html/index.html
        content: |
          <h1>Welcome to {{ inventory_hostname }}</h1>
          <p>Deployed via Ansible by {{ my_name }}</p>

# PLAY 2 — Install Git on Ubuntu Clients
- name: Install Git
  hosts: ubuntu_clients
  become: yes
  tasks:
    - name: Install Git
      apt:
        name: git
        state: present

# PLAY 3 — Display Name on All Hosts
- name: Display My Name on All Hosts
  hosts: all
  vars:
    my_name: "Ebsiy Anslem"
  tasks:
    - name: Show name using debug
      debug:
        msg: "Hello from {{ inventory_hostname }} — My name is {{ my_name }}"

